# Generated by Django 5.0.7 on 2026-05-30 02:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School')], max_length=3, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('caption', models.CharField(help_text='e.g., Grades 7-10', max_length=100)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='IDTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., SY 2025-2026 Template', max_length=100)),
                ('background_path', models.CharField(help_text='Path to background image', max_length=500)),
                ('font_color', models.CharField(default='#FFFFFF', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=False, help_text='Only one template can be active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'id_templates',
            },
        ),
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('type', models.CharField(choices=[('school_day', 'School Day'), ('holiday', 'Holiday'), ('suspension', 'Suspension')], default='school_day', max_length=20)),
                ('label', models.CharField(blank=True, help_text='e.g., Rizal Day', max_length=200, null=True)),
            ],
            options={
                'db_table': 'school_calendar',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default="St. Mary's Academy", max_length=255)),
                ('school_year', models.CharField(default='2025-2026', max_length=20)),
                ('school_logo_path', models.CharField(blank=True, max_length=500, null=True)),
                ('current_quarter', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('current_week', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('sf2_target_attendance', models.DecimalField(decimal_places=2, default=95.0, help_text='Target attendance percentage', max_digits=5)),
                ('q1_start', models.DateField(blank=True, null=True)),
                ('q1_end', models.DateField(blank=True, null=True)),
                ('q2_start', models.DateField(blank=True, null=True)),
                ('q2_end', models.DateField(blank=True, null=True)),
                ('q3_start', models.DateField(blank=True, null=True)),
                ('q3_end', models.DateField(blank=True, null=True)),
                ('q4_start', models.DateField(blank=True, null=True)),
                ('q4_end', models.DateField(blank=True, null=True)),
                ('messenger_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('sms_credits_remaining', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
                'db_table': 'school_settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin (Principal/Registrar)'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('messenger_psid', models.CharField(blank=True, help_text='Facebook Page-Scoped ID', max_length=50, null=True)),
                ('subject_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(12)])),
                ('label', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='core.department')),
            ],
            options={
                'db_table': 'grade_levels',
                'ordering': ['level'],
                'unique_together': {('department', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.CharField(help_text='12-digit Learner Reference Number', max_length=12, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12)])),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=1)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('gpa', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage 0-100', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('photo_path', models.CharField(blank=True, help_text='Path to student photo', max_length=500, null=True)),
                ('barcode_value', models.CharField(help_text='Same as LRN', max_length=12)),
                ('barcode_active', models.BooleanField(default=True, help_text='False for graduates')),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_messenger_psid', models.CharField(blank=True, max_length=50, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('parent_account', models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user_account', models.OneToOneField(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learners',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='IDPrintQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('new_enrollment', 'New Enrollment'), ('lost', 'Lost'), ('damaged', 'Damaged'), ('renewal', 'Renewal')], default='new_enrollment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('printed', 'Printed')], default='pending', max_length=20)),
                ('pdf_path', models.CharField(blank=True, help_text='Path to generated PDF', max_length=500, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_requests', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.idtemplate')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_print_requests', to='core.learner')),
            ],
            options={
                'db_table': 'id_print_queue',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ConductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.TextField(help_text='Description of the conduct/behavior')),
                ('type', models.CharField(choices=[('Positive', 'Positive'), ('Note', 'Note'), ('Warning', 'Warning')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_conducts', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conduct_logs', to='core.learner')),
            ],
            options={
                'db_table': 'conduct_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('messenger', 'Facebook Messenger'), ('sms', 'SMS'), ('system', 'System')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('message', models.TextField()),
                ('triggered_by', models.CharField(choices=[('attendance_scan', 'Attendance Scan'), ('grade_posted', 'Grade Posted'), ('absence_warning', 'Absence Warning'), ('system', 'System')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.learner')),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_records',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Guardian', 'Guardian')], max_length=20)),
                ('messenger_linked', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Sampaguita, St. Jude', max_length=100)),
                ('strand', models.CharField(blank=True, choices=[('STEM', 'Science, Technology, Engineering, and Mathematics'), ('ABM', 'Accountancy, Business, and Management'), ('HUMSS', 'Humanities and Social Sciences'), ('GAS', 'General Academic Strand'), ('TVL-ICT', 'Technical-Vocational-Livelihood - ICT'), ('TVL-HE', 'Technical-Vocational-Livelihood - Home Economics')], help_text='SHS only', max_length=10, null=True)),
                ('adviser', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.gradelevel')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='learner',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners', to='core.section'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Mathematics 7, General Physics I', max_length=100)),
                ('quarter_weight_quiz', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('quarter_weight_exam', models.DecimalField(decimal_places=2, default=40.0, max_digits=5)),
                ('quarter_weight_activity', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.section')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['section', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in_morning', models.TimeField(blank=True, null=True)),
                ('time_out_morning', models.TimeField(blank=True, null=True)),
                ('time_in_afternoon', models.TimeField(blank=True, null=True)),
                ('time_out_afternoon', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.learner')),
            ],
            options={
                'db_table': 'attendance_records',
                'ordering': ['-date', 'learner'],
                'unique_together': {('learner', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('activity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('computed_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.learner')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.subject')),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['learner', 'subject', 'quarter'],
                'unique_together': {('learner', 'subject', 'quarter')},
            },
        ),
    ]
