# Generated by Django 5.0.7 on 2026-05-30 03:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="School display name, e.g. St. Mary's Academy", max_length=255)),
                ('subdomain', models.CharField(help_text='e.g. stmarys → stmarys.educardpro.com', max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='basic', max_length=20)),
                ('plan_expires_at', models.DateTimeField(blank=True, help_text='Null = active indefinitely (testing/enterprise)', null=True)),
                ('setup_fee_paid', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sms_credits_remaining', models.IntegerField(default=0)),
                ('messenger_conversations_used', models.IntegerField(default=0, help_text="Current month's Messenger conversation count")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='q1_end',
            new_name='grading_period_1_end',
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='q2_end',
            new_name='grading_period_1_start',
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='q1_start',
            new_name='grading_period_2_end',
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='q2_start',
            new_name='grading_period_2_start',
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='q3_end',
            new_name='grading_period_3_end',
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='q3_start',
            new_name='grading_period_3_start',
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='q4_end',
            new_name='grading_period_4_end',
        ),
        migrations.RenameField(
            model_name='schoolsettings',
            old_name='q4_start',
            new_name='grading_period_4_start',
        ),
        migrations.AddField(
            model_name='learner',
            name='graduation_status',
            field=models.CharField(choices=[('active', 'Active'), ('candidate', 'Graduation Candidate'), ('confirmed', 'Confirmed Graduate'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='messenger_conversations_used',
            field=models.IntegerField(default=0, help_text='Monthly Messenger conversation count'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='plan',
            field=models.CharField(default='basic', help_text='starter, basic, standard, premium, enterprise', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='primary_color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code for branding', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Consecutive failed login attempts; lock after 5'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account locked until this datetime', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Set when user confirms 2FA setup', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key (base32 encoded)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='messenger_psid',
            field=models.CharField(blank=True, help_text='Facebook Page-Scoped ID for Messenger notifications', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('learner_created', 'Learner Created'), ('learner_updated', 'Learner Updated'), ('learner_deleted', 'Learner Soft-Deleted'), ('learner_photo_uploaded', 'Learner Photo Uploaded'), ('grade_updated', 'Grade Updated'), ('grade_bulk_imported', 'Grades Bulk Imported'), ('attendance_scanned', 'Attendance Scanned'), ('attendance_manual', 'Attendance Manually Edited'), ('id_generated', 'ID Card Generated'), ('id_printed', 'ID Card Marked Printed'), ('id_reprint_requested', 'ID Reprint Requested'), ('graduation_confirmed', 'Graduation Confirmed'), ('settings_updated', 'Settings Updated'), ('calendar_updated', 'School Calendar Updated'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_2fa_enabled', '2FA Enabled')], max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of what changed')),
                ('subject_model', models.CharField(blank=True, help_text='e.g., Learner, Grade, Section', max_length=50, null=True)),
                ('subject_id', models.IntegerField(blank=True, help_text='PK of the affected record', null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Field values before the change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Field values after the change', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('grades', 'Grade Import'), ('learners', 'Learner Import')], max_length=20)),
                ('file_path', models.CharField(help_text='Path to uploaded file', max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of row-level errors: [{row, lrn, error}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_import_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(help_text='quiz_score, exam_score, or activity_score', max_length=50)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.grade')),
            ],
            options={
                'db_table': 'grade_audit_logs',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('messenger', 'Facebook Messenger'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_notification', to='core.learner')),
            ],
            options={
                'db_table': 'graduation_notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.learner')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessengerWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(help_text='Facebook Page-Scoped ID of the sender', max_length=50)),
                ('event_type', models.CharField(choices=[('message', 'Incoming Message'), ('postback', 'Postback'), ('optin', 'Opt-In'), ('referral', 'Referral')], max_length=20)),
                ('ref_param', models.CharField(blank=True, help_text='ref= value from m.me opt-in link', max_length=100, null=True)),
                ('raw_payload', models.JSONField(help_text='Full webhook payload from Meta')),
                ('processed', models.BooleanField(default=False, help_text='True once PSID has been saved to learner')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('matched_learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messenger_events', to='core.learner')),
            ],
            options={
                'db_table': 'messenger_webhook_events',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0.5, help_text='Cost in PHP', max_digits=5)),
                ('provider', models.CharField(default='Semaphore', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='core.learner')),
            ],
            options={
                'db_table': 'sms_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSCreditBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_added', models.IntegerField(choices=[(1000, '1,000 SMS Credits'), (2200, '2,200 SMS Credits')])),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in PHP', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(help_text='Super Admin who added the credits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_credit_additions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_bundles', to='core.tenant')),
            ],
            options={
                'db_table': 'sms_credit_bundles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Full domain, e.g. stmarys.educardpro.com', max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=True, help_text='Primary domain used for routing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.tenant')),
            ],
            options={
                'db_table': 'tenant_domains',
                'ordering': ['domain'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.IntegerField(choices=[(5, '5 Consecutive Days'), (10, '10 Consecutive Days')], help_text='5 or 10 consecutive absent days')),
                ('streak_start_date', models.DateField(help_text='First day of the consecutive absence streak')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(choices=[('messenger', 'Messenger'), ('sms', 'SMS')], default='messenger', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_alerts', to='core.learner')),
            ],
            options={
                'db_table': 'absence_alerts',
                'ordering': ['-notified_at'],
                'unique_together': {('learner', 'threshold', 'streak_start_date')},
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='e.g., 2025-2026', max_length=20)),
                ('pdf_path', models.CharField(blank=True, help_text='Storage path to the generated PDF', max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='core.learner')),
            ],
            options={
                'db_table': 'report_cards',
                'ordering': ['-generated_at'],
                'unique_together': {('learner', 'school_year')},
            },
        ),
    ]
