# Generated by Django 5.0.7 on 2026-05-30 03:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerSectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='e.g. 2025-2026', max_length=20)),
                ('reason', models.CharField(choices=[('enrollment', 'Initial Enrollment'), ('promotion', 'Promoted to Next Grade'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('retained', 'Retained / Repeated Grade')], default='enrollment', max_length=20)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_history', to='core.learner')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_history_entries', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_history', to='core.section')),
            ],
            options={
                'db_table': 'learner_section_history',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messenger_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('attendance_alerts', models.BooleanField(default=True, help_text='Notify on every attendance scan')),
                ('grade_notifications', models.BooleanField(default=True, help_text='Notify when teacher posts grades')),
                ('absence_warnings', models.BooleanField(default=True, help_text='Notify on 5-day and 10-day absence streaks')),
                ('conduct_alerts', models.BooleanField(default=True, help_text='Notify when a conduct log is added')),
                ('muted_until', models.DateTimeField(blank=True, help_text='All notifications suppressed until this datetime', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.learner')),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='PortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_type', models.CharField(choices=[('student', 'Student Portal'), ('parent', 'Parent Portal')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('token_jti', models.CharField(blank=True, help_text='JWT token ID — used to invalidate specific sessions', max_length=36, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portal_sessions',
                'ordering': ['-logged_in_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='e.g. INV-2026-001', max_length=50, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('line_items', models.JSONField(default=list, help_text='[{description, quantity, unit_price, total}]')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='VAT or applicable tax in PHP', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Super Admin who generated the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.tenant')),
            ],
            options={
                'db_table': 'subscription_invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDCardElementPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(choices=[('photo', 'Student Photo'), ('full_name', 'Full Name'), ('lrn', 'LRN Text'), ('section_label', 'Section Label'), ('barcode', 'Barcode'), ('qr_code', 'QR Code'), ('school_logo', 'School Logo'), ('school_name', 'School Name'), ('school_year', 'School Year')], max_length=20)),
                ('x', models.IntegerField(help_text='X position in pixels from left edge')),
                ('y', models.IntegerField(help_text='Y position in pixels from top edge')),
                ('width', models.IntegerField(help_text='Width in pixels')),
                ('height', models.IntegerField(help_text='Height in pixels')),
                ('font_size', models.IntegerField(default=12, help_text='Font size in pt')),
                ('font_bold', models.BooleanField(default=False)),
                ('font_color', models.CharField(default='#000000', help_text='Overrides template font_color for this element', max_length=7)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_positions', to='core.idtemplate')),
            ],
            options={
                'db_table': 'id_card_element_positions',
                'ordering': ['template', 'element'],
                'unique_together': {('template', 'element')},
            },
        ),
        migrations.CreateModel(
            name='SF1Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('enrollment_status', models.CharField(choices=[('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('transferred', 'Transferred'), ('completed', 'Completed')], default='enrolled', max_length=20)),
                ('age_as_of_june', models.IntegerField(blank=True, help_text="Learner's age as of June 1 of the school year", null=True)),
                ('is_indigenous_people', models.BooleanField(default=False)),
                ('is_4ps_beneficiary', models.BooleanField(default=False, help_text='Pantawid Pamilyang Pilipino Program beneficiary')),
                ('is_returning_learner', models.BooleanField(default=False)),
                ('mother_tongue', models.CharField(blank=True, max_length=50, null=True)),
                ('date_enrolled', models.DateField(blank=True, null=True)),
                ('date_dropped', models.DateField(blank=True, null=True)),
                ('drop_reason', models.TextField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf1_records', to='core.learner')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sf1_records', to='core.section')),
            ],
            options={
                'db_table': 'sf1_records',
                'ordering': ['-school_year', 'learner__last_name'],
                'unique_together': {('learner', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='SF2Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=20)),
                ('month', models.IntegerField(help_text='Month number (1=January … 12=December)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(help_text='Calendar year, e.g. 2026')),
                ('total_school_days', models.IntegerField(default=0)),
                ('total_male_enrolled', models.IntegerField(default=0)),
                ('total_female_enrolled', models.IntegerField(default=0)),
                ('average_daily_attendance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage — compared against SF2 95% target', max_digits=5)),
                ('meets_sf2_target', models.BooleanField(default=False)),
                ('pdf_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('submitted', 'Submitted to DepEd')], default='draft', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sf2_reports', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf2_reports', to='core.section')),
            ],
            options={
                'db_table': 'sf2_reports',
                'ordering': ['-year', '-month', 'section'],
                'unique_together': {('section', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TeacherSectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='e.g. 2025-2026 — allows historical records', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='False when teacher is reassigned mid-year')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.section')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='section_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_section_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('teacher', 'section', 'school_year')},
            },
        ),
    ]
