# Generated by Django 5.0.7 on 2026-05-30 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phase_complete_remaining_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYearConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='e.g. 2025-2026', max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False, help_text='Only one year can be current')),
                ('q1_start', models.DateField()),
                ('q1_end', models.DateField()),
                ('q2_start', models.DateField()),
                ('q2_end', models.DateField()),
                ('q3_start', models.DateField()),
                ('q3_end', models.DateField()),
                ('q4_start', models.DateField()),
                ('q4_end', models.DateField()),
                ('total_school_days', models.IntegerField(default=0)),
                ('enrollment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'school_year_configs',
                'ordering': ['-school_year'],
            },
        ),
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('enrollment', 'Enrollment Application'), ('lrn_reprint', 'LRN Reprint Request'), ('sf1_export', 'SF1 Report Generation'), ('photo_update', 'Student Photo Update'), ('id_reprint', 'ID Card Reprint'), ('sf2_submit', 'SF2 Submission'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_tasks', to='core.learner')),
            ],
            options={
                'db_table': 'admin_tasks',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('messenger_username', models.CharField(blank=True, help_text='e.g. @aurora.aquino', max_length=100, null=True)),
                ('facebook_url', models.CharField(blank=True, help_text='e.g. fb.com/aurora.aquino.teacher', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('show_phone', models.BooleanField(default=True)),
                ('show_messenger', models.BooleanField(default=True)),
                ('show_facebook', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_contacts',
            },
        ),
    ]
