# Generated by Django 5.0.7 on 2026-05-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_relationship_fixes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='learnerparent',
            name='unique_learner_parent',
        ),
        migrations.AlterField(
            model_name='department',
            name='key',
            field=models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School'), ('SPL', 'Special Programme'), ('ALS', 'Alternative Learning System')], max_length=3, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='learnerparent',
            unique_together={('learner', 'parent')},
        ),
    ]
